### ISSUE TITLE
The parsing of the second level tag

### ISSUE THREAD

**Issue by Jie9527** [hisenyuan/EMVCo-SGQR-encode-decode-crc#1]
First of all, thank you very much! Your project has been very helpful to me. Now I have a question about parsing the second level tag. As you can see, DEFAULT_START_TAG is "00" to be resolved, how do you resolve that DEFAULT_START_TAG is not "00"? Looking forward to your reply. Thanks again!

**Comment by hisenyuan** [comment]
according to TLV data structure, DEFAULT_START_TAG must start "00". can you give me the qr code img?

**Comment by Jie9527** [comment]
> according to TLV data structure, DEFAULT_START_TAG must start "00". can you give me the qr code img?
A qr code from the official website of EMVCo.
![466286BB-7C46-46BA-83C8-D71019C107CB](https://user-images.githubusercontent.com/26648685/77139307-72bd0500-6ab0-11ea-8efc-591d2fc0e536.png)

**Comment by hisenyuan** [comment]
it's emvco payment qr code? 

> 00020101021229300012D156000000000510A93FO3230Q31280012D15600000001030812345678520441115802CN5914BEST TRANSPORT6007BEIJING64200002ZH0104最佳运输0202北京540523.7253031565502016233030412340603***0708A60086670902ME91320016A0112233449988770708123456786304A13A

**Comment by Jie9527** [comment]
You can see that the secondary tag for Tag62 starts with 03

**Comment by hisenyuan** [comment]
Maybe it's not a tlv, according to below doc 4.8, tag 62 mean additional data. how to decode it depends on the data structure which put by merchant.

> com/hisen/emvco/docs/EMVCo-Merchant-Presented-QR-Specification-v1-1.pdf

**Comment by Jie9527** [comment]
Thank you! Perhaps this is an additional data that needs to be parsed separately and cannot be used in a generic way.
